apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: "https://vault.vault.svc.cluster.local:8200"
      path: "secret"
      version: "v2"
      caProvider:
        type: Secret
        name: vault-tls
        namespace: vault
        key: ca.crt
      auth:
        tokenSecretRef:
          name: vault-token
          namespace: external-secrets
          key: token
