apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - traefik/helmrelease.yaml
  - metallb/helmrelease.yaml
  - metallb/config.yaml
  - cert-manager/helmrelease.yaml
  - cert-manager/cluster-issuer.yaml
  - cnpg/helmrelease.yaml
  - flux/gitops-source.yaml
  - vcluster/helmrelease.yaml
  - coredns/deployment.yaml
